spring:
  application:
    name: blood-sample-management-system

  datasource:
    driver-class-name:  om.mysql.cj.jdbc.Driver
    url:  jdbc:mysql://localhost:3306/springboot_productDB?createDatabaseIfNotExist=true
    username :  root
    password :  tiger
  jpa:
    hibernate.ddl-auto : update
    show-sql : true
    properties.hibernate.dailect : org.hibernate.dailect.MySQL8Dialect
server:
  port : 8081
    
    







